=  Java Container Awareness
:page-audio-src: index.wav
:page-transcript-src: index.txt
:navtitle: Home

== Introduction

Course Title:  Java Container Awareness

Course description: This course provides a practical introduction to running Java applications as a fully containerized application, with a focus on resource detection and memory management inside a container.
Learn how Java applications containerized applications integrate with Kubernetes and OpenShift and how to identify common runtime and resource-related issues.
Explore essential troubleshooting techniques and tools for containerized Java workloads.

Duration: 2 Hours

== Topics covered in this course


*  Introduction to Containerized Java

*  Container Resource Detection

*  Risks and Memory Management

*  OpenShift and Kubernetes Integration

*  Troubleshooting and Tooling

*  Hands-on Lab

== Prerequisites

This course assumes that you have the following prior experience:

* Experience with Java (in general) and heap (off-heap) allocation
* Experience with container orchestrators, such as Openshift in terms of deployment, not necessarily with Operators

NOTE: **Use of Artificial Intelligence:**
This publication contains content or media that is generated or assisted by AI tools. The Training deliverables have primarily human authorship, and all content was reviewed by an human domain expert.
